version: '3'

services:
  wordpress:
    restart: always
    container_name: wordpress
    build: wordpress
    env_file:
        - configuration/settings.env
    volumes:
        - ./wordpress/data:/var/www/html